### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by mikhoul** [ptytb/pips#1]
When I start the program there is those errors in the console windows:

```
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Exception calling "ExtractAssociatedIcon" with "1" argument(s): "La valeur de 'null' n'est pas valide pour
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:776 char:5
+     $form.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($iconPa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
dir : Cannot find path 'C:\Users\Michel\AppData\Local\Programs\Python' because it does not exist.
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:383 char:20
+     foreach ($d in dir "$env:LOCALAPPDATA\Programs\Python") {
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Michel...Programs\Python:String) [Get-ChildItem],
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

```
I use latest Python 3.6.4 32bit under Windows 7 x64
It is installed in K:\Python

If you need more information just ask me, I'm new to python.

Regards :octocat:

**Comment by ptytb** [comment]
Thank you,

It was expecting pip.exe available in %PATH% to take its icon for a window.
I've embedded an icon into the script, so it should be working now.

**Comment by mikhoul** [comment]
Screenshot of the program itself when I try to list the installed packages: https://i.imgur.com/w4x86iT.png

**Comment by mikhoul** [comment]
I just see you answered I will try it right now and report ....

**Comment by mikhoul** [comment]
Oups @ptytb  There is one less error but the "big" one is always there, 

```
dir : Cannot find path 'C:\Users\Michel\AppData\Local\Programs\Python' because it does not exist.
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:418 char:20
+     foreach ($d in dir "$env:LOCALAPPDATA\Programs\Python") {
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Michel...Programs\Python:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Exception calling "Invoke" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:170 char:25
+     $button.Add_Click({ $handler.Invoke( @($Script:button) ) }.GetNew ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException


```
Screenshot: https://i.imgur.com/2Bkkv6v.png

To help you a little bit more here's my paths for Python: https://i.imgur.com/bQscJTS.png

There is **NO** "_C:\Users\Michel\AppData\Local\Programs\Python_" on my system.

If you need more info just let me know. :smile: 

Regards :octocat:

**Comment by ptytb** [comment]
Okay, I've added search for Python installations via Windows registry, that should work.

**Comment by mikhoul** [comment]
@ptytb   Small problem again:

```
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
dir : Cannot find path 'HKEY_CURRENT_USER\Software\Python' because it does not exist.
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:428 char:20
+     $reg_pythons = dir HKCU:Software\Python | foreach { dir HKCU:$_ } ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CURRENT_USER\Software\Python:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

```

Maybe you could find the path more reliably using **Environment path** in the registry with:
_**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment**_
Like here: https://i.imgur.com/GH6cBHP.png

Or use "**HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\3.6-32\InstallPath**" but IMO it would be less reliable than using the Key for the Paths cause they are the same in all windows version/system and you don't have to worry about Windows **32bit** or **64bit** installation. 

Regards :octocat:

**Comment by ptytb** [comment]
I've added key existence test, please try it. This approach for finding Python in registry is recommend with PEP standard so I'm using it. Regarding PATH variable, if your Python is enlisted in user PATH, it should be detected; in case of system PATH you have to re-login.

**Comment by mikhoul** [comment]
It seem to work now 👍

The only message remaining in the cmd/console window is:  
`Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).`

The reason I was suggesting to use the "PATH variable" it's because it is always there, also the same on all version of Pythons and don't change from  Win 32bit/64 version.

I'm new to Python so I don't know about PEP standard so I could be wrong 😏

I will try it more thoroughly tonight or tomorrow and let you know if I see something unusual.


Regards :octocat:

**Comment by mikhoul** [comment]
@ptytb 

I was tring to install wxPython package but it don't work or I don't know how to do it ? 

Here's a screencast to show you what I do and what happen, it will be more easy that trying to explain it to you 😉   http://screencast-o-matic.com/watch/cFn3nNoRF3

**Also a small request:** Could you add a button to the GUI to delete packages cleanly, sometime I try new Python program  that need other package but just to found that the Python program don't work as expected so with the time I have to many packages for nothing and I need to clean them up.

Regards and thanks again for  your quick answer. :octocat:

**Comment by ptytb** [comment]
Merci beaucoup for detailed report, you're amazing tester,

After having wxPython and other packages chosen, you were supposed to choose and execute Install. Now, I've added the Install button to the dialog as lazy shortcut.

As for deleting packages, you can select the Uninstall action and hit Execute, that should do exactly you're expecting for.

A piece of advice, if you don't want to contaminate your python installation with stray packages, you may want to use virtualenv.

**Comment by mikhoul** [comment]
Ah I understand better now how it work :smile: 

I was not "catching" that the execute button was tied with the dropdown menu. 
 Maybe for newbies like me you could add to the GUI something like a line around the "execute" button and the dropdown menu to indicate more clearly that they work together.

Something like this: https://i.imgur.com/41j0xso.png

Also with the new version I had more error messages at the start of the program: 

```
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Michel\Desktop\Pips-Gui\pips.psm1:425 char:51
+         Get-InterpreterRecord (Split-Path -Parent $path) $items
+                                                   ~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
```
 
Another small thing I've seen when I was testing to install package a package would not install and return an error, I'm not sure if it is an error of the program or the package itself:  https://i.imgur.com/y7Fx5nz.png

Have a nice day !  :octocat:

**Comment by ptytb** [comment]
Thank you for response,

I've been thinking about this visual grouping too, so it is there now. As for "isolated" checkbox, not sure it is actually needed, so you can just ignore it for now.

Fixed empty path error when searching for Pythons.

I was not able to install xrpi-test-12.10.16 from pip, so message saying installation failed is being shown with right reason.

Thanks again for scrupulous testing.
